// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreatePartyResult struct {
	Name      string `json:"name"`
	AdminCode string `json:"adminCode"`
}

type DatePartySettings struct {
	VotingEnabled  bool `json:"votingEnabled"`
	OptionsEnabled bool `json:"optionsEnabled"`
}

type LocationPartySettings struct {
	VotingEnabled  bool `json:"votingEnabled"`
	OptionsEnabled bool `json:"optionsEnabled"`
}

type PartySettings struct {
	Dates     *DatePartySettings     `json:"dates"`
	Locations *LocationPartySettings `json:"locations"`
}
